'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace AppLinqMantenimiento

    Partial Public Class Equipos
        Public Property CodInstalacion As String
        Public Property Procesador As String
        Public Property Velocidad As Nullable(Of Short)
        Public Property CDROM As Nullable(Of Byte)
        Public Property Memoria As Short
        Public Property TarjetaRed As String
        Public Property DiscoDuro As Single
        Public Property Uso As Boolean
    
    End Class

End Namespace
