'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace AppLinqMantenimiento

    Partial Public Class Instalaciones
        Public Property CodInstalacion As String
        Public Property CodEquipo As String
        Public Property CodSoftware As String
        Public Property FechaInstalacion As Nullable(Of Date)
    
    End Class

End Namespace
